#! /bin/sh

polybar &
picom &
nitrogen --restore &
# playerctld

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 󰣇      

bspc config border_width 2
bspc config border_round 2
bspc config window_gap 6

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#F0C674'

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
